#!/usr/bin/env bash

set -euo pipefail
# ====== EDIT THIS YAML CONTENT AS NEEDED ======
YAML_CONTENT=$(cat <<'EOF'
# Generated by Butane; do not edit
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: 98-data-partition
spec:
  config:
    ignition:
      version: 3.4.0
    storage:
      disks:
        - device: /dev/nvme0n1
          partitions:
            - label: data
              startMiB: 100000
EOF
)
echo "Adding: "
echo $YAML_CONTENT
# ========== END EDIT ==========
if [[ $# -lt 2 ]]; then
  echo "Usage: $0 input.json output.json"
  exit 1
fi
INPUT_JSON="$1"
OUTPUT_JSON="$2"
BASE64_DATA=$(printf "%s" "$YAML_CONTENT" | base64 | tr -d '\n')
# Construct two jq objects with different path fields
JQ_OBJECTS=$(jq -n \
  --arg b64 "$BASE64_DATA" \
  '
    [
      {
        overwrite: true,
        path: "/opt/openshift/manifests/98-data-partition.yaml",
        user: { name: "root" },
        contents: { source: ("data:text/plain;charset=utf-8;base64," + $b64) },
        mode: 420
      },
      {
        overwrite: true,
        path: "/opt/openshift/openshift/98-data-partition.yaml",
        user: { name: "root" },
        contents: { source: ("data:text/plain;charset=utf-8;base64," + $b64) },
        mode: 420
      }
    ]
  '
)
echo "Final Objects:"
echo $JQ_OBJECTS
# Add both objects to root.storage.files[]
jq -c \
  --argjson newfiles "$JQ_OBJECTS" \
  '
    .storage.files += $newfiles
  ' "$INPUT_JSON" > "$OUTPUT_JSON"
